FROM arm64v8/rust as planner
WORKDIR rustdemo
# We only pay the installation cost once, 
# it will be cached from the second build onwards
# To ensure a reproducible build consider pinning 
# the cargo-chef version with `--version X.X.X`
RUN cargo install cargo-chef 
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM arm64v8/rust as cacher
WORKDIR rustdemo
RUN cargo install cargo-chef
COPY --from=planner /rustdemo/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM arm64v8/rust as builder
WORKDIR rustdemo
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /rustdemo/target target
COPY --from=cacher /usr/local/cargo /usr/local/cargo
RUN cargo build --release --bin rustdemo --target aarch64-unknown-linux-gnu

FROM arm64v8/debian:buster-slim as runtime
WORKDIR rustdemo
COPY --from=builder /rustdemo/target/aarch64-unknown-linux-gnu/release/rustdemo .
CMD ["./rustdemo"]