# our final base
FROM arm64v8/debian:stable-slim

# copy the build artifact from the build stage
COPY ./target/aarch64-unknown-linux-gnu/release/rustdemo .

# set the startup command to run your binary
CMD ["./rustdemo"]